name: secrets pracice
on:
  workflow_dispatch

jobs:
  secrets-testing:
    runs-on: ubuntu-latest
    env:
      var: "hello welcome"
    steps:
      - name: print actor name
        run: echo "Hello ${{github.actor}}, ${var}}"